[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "app/api"

# Ensure this config takes precedence
[context.production]
  command = "chmod +x build.sh && ./build.sh"
  publish = ".next" 